version: '3.8'

services:
  datanode:
    restart: unless-stopped
    build:
      context: ./datanode
    image: 192.168.2.1:5000/datanode
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    volumes:
      - datanode:/hadoop/dfs/data
  namenode:
    restart: unless-stopped
    build:
      context: ./namenode
    image: 192.168.2.1:5000/namenode
    ports:
      - 9870:9870
      - 9000:9000
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    volumes:
      - namenode:/hadoop/dfs/name

  resourcemanager:
    restart: unless-stopped
    build:
      context: ./resourcemanager
    image: 192.168.2.1:5000/resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
  nodemanager:
    restart: unless-stopped
    build:
      context: ./nodemanager
    image: 192.168.2.1:5000/nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
  historyserver:
    restart: unless-stopped
    build:
      context: ./historyserver
    image: 192.168.2.1:5000/historyserver
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    ports:
      - 8188:8188
    volumes:
      - historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
  executor:
    container_name: localExecutor
    build:
      context: ./executor
    image: 192.168.2.1:5000/executor
    volumes:
      - ./executor/package:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
    env_file:
      - hadoop.env

volumes:
  namenode:
  datanode:
  historyserver:
