version: "3.8"

services:
  postgres:
    restart: always
    build:
      context: ./postgres
    image: 192.168.2.1:5000/data_collection_postgres
    command: -c 'config_file=/postgresql.conf'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_DB=data_collection_db
      - POSTGRES_PASSWORD=passwd
    volumes:
      - type: volume
        source: pg-data
        target: /var/lib/postgresql/data/
      # - type: bind
      #   source: ./postgres/pgsql-data
      #   target: /var/lib/postgresql/data/
    deploy:
      placement:
        constraints:
          - "node.labels.exit==yes"
  fastapi:
    restart: always
    build: ./api
    image: 192.168.2.1:5000/data_collection_api
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--reload"
      ]
    environment:
      - DB_USER=fastapi
      - DB_PASS=passwd
      - DB_URL=postgres
      - DB_DBNAME=data_collection_db
    ports:
      - 8000:8000
    deploy:
      placement:
        constraints:
          - "node.labels.exit==yes"


volumes:
  pg-data:
